# Generated by Django 6.0.1 on 2026-02-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(default='', max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Contraseña')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['-created'],
            },
        ),
    ]
